[package]
name = "greetings_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
utoipa = { version = "4", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "4", features = ["actix-web"] }
chrono = { version = "0.4", features = ["serde"] }
sqlx = { version = "0.7", features = [ "runtime-tokio" , "sqlite", "chrono"] }
thiserror = "1.0.47"
validator = "0.16.1"
validator_derive = "0.16.0"
derive_more = "0.99.0"
uuid = "1.3.1"
env_logger = "0.10.0"