openapi: 3.0.0
info:
    title: Greetings API
    description: The app receives and lists greetings from producers
    version: 0.1.9

servers:
    - url: http://api.example.com/v1
      description: Optional server description, e.g. Main (production) server
    - url: http://staging-api.example.com
      description: Optional server description, e.g. Internal staging server for testing

paths:
    /greeting:
        get:
            summary: Returns a list of greetings.
            description: Optional extended description in CommonMark or HTML.
            responses:
                '200':    # status code
                    description: A JSON array of greetings received in order
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Greeting'
        put:
            summary: Stores a new greeting message
            responses:
                '201':
                    description: A greeting JSON formatted document
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Greeting'
components:
    schemas:
        Greeting:
            type: object
            properties:
                from:
                    type: string
                to:
                    type: string
                message:
                    type: string




