[kafka_consumer]
broker = "localhost:29092"
topic = "greetings.public.greeting_logg"
consumer_group = "greeting_consumers"
message_timeout_ms = 5000
enable_idempotence = true
processing_guarantee = "exactly_once"
number_of_consumers = 10
[database]
url = "postgres://test:test@test:5432/test"
host = "test:5432"
database = "test"
user = "test"
password = "test"
