[kafka]
broker = "localhost:9092"
topic = "greetings"
message_timeout_ms = 5000
enable_idempotence = true
processing_guarantee = "exactly_once"
[database]
url = "postgres://greeting_rust:greeting_rust@test:5432/greeting_rust"
