apiVersion: apps/v1
kind: Deployment
metadata:
    name: greeting-rust
spec:
    selector:
        matchLabels:
            app: greeting-rust
    template:
        metadata:
            labels:
                app: greeting-rust
        spec:
            containers:
                -   name: greeting-rust
                    image: arnecdn/greeting-rust:0.11
                    imagePullPolicy: IfNotPresent

                    ports:
                        -   containerPort: 8080
                    env:
                        -   name: APP_DATABASE_DATABASE
                            valueFrom:
                                configMapKeyRef:
                                    key: POSTGRES_DB
                                    name: postgres-greeting-config
                        -   name: APP_DATABASE_USER
                            valueFrom:
                                configMapKeyRef:
                                    key: POSTGRES_USER
                                    name: postgres-greeting-config
                        -   name: APP_DATABASE_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    key: POSTGRES_PASSWORD
                                    name: postgres-greeting-secret
                        - name: APP_DATABASE_URL
                          value: "postgres://$(APP_DATABASE_USER):$(APP_DATABASE_PASSWORD)@postgres-greeting:5432/$(APP_DATABASE_DATABASE)"

---
apiVersion: v1
kind: Service
metadata:
    name: greeting-rust
spec:
    ports:
        - port: 8080
    selector:
        app: greeting-rust
