apiVersion: apps/v1
kind: Deployment
metadata:
    name: greeting-rust
spec:
    selector:
        matchLabels:
            app: greeting-rust
    template:
        metadata:
            labels:
                app: greeting-rust
        spec:
            containers:
                -   name: greeting-rust
                    image: arnecdn/greeting-rust:latest
                    ports:
                        -   containerPort: 8080
                    env:
                        -   name: POSTGRES_DB
                            valueFrom:
                                configMapKeyRef:
                                    key: POSTGRES_DB
                                    name: postgres-greeting-config
                        -   name: POSTGRES_USER
                            valueFrom:
                                configMapKeyRef:
                                    key: POSTGRES_USER
                                    name: postgres-greeting-config
                        -   name: POSTGRES_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    key: POSTGRES_PASSWORD
                                    name: postgres-greeting-secret
---
apiVersion: v1
kind: Service
metadata:
    name: greeting-rust
spec:
    ports:
        - port: 8080
    selector:
        app: greeting-rust
