apiVersion: apps/v1
kind: Deployment
metadata:
    name: greeting-rust
spec:
    replicas: 1
    selector:
        matchLabels:
            app: greeting-rust
    template:
        metadata:
            labels:
                app: greeting-rust
        spec:
            containers:
                -   name: greeting-rust
                    image: arnecdn/greeting-rust:0.1
                    imagePullPolicy: IfNotPresent
                    resources:
                        requests:
                            memory: "8Mi"
                            cpu: "10m"
                        limits:
                            cpu: "500m"
                            memory: "16Mi"
                    ports:
                        -   containerPort: 8080
                    env:

                        - name: APP__KAFKA__BROKER
                          value: "kafka-service:9093"
                        - name: APP__KAFKA__TOPIC
                          value: "greetings"
                        - name: APP__KAFKA__CONSUMER_GROUP
                          value: "greeting_consumers"
                        - name: APP__KAFKA__MESSAGE_TIMEOUT_MS
                          value: "5000"
                        - name: APP__KAFKA__ENABLE_IDEMPOTENCE
                          value: "true"
                        - name: APP__OTEL_COLLECTOR__OLTP_ENDPOINT
                          value: "http://my-opentelemetry-collector:4317"
                        - name: APP__KUBE__MY_POD_NAME
                          valueFrom:
                            fieldRef:
                             fieldPath: metadata.name

                    command:
                              - "/usr/bin/server"


---
apiVersion: v1
kind: Service
metadata:
    name: greeting-rust-service
spec:
    ports:
        - port: 8080
          targetPort: 8080
#          nodePort: 32002
    selector:
        app: greeting-rust
    type: LoadBalancer
#    externalIPs:
#      - 192.168.64.2
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greeting-rust-ingress
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: greeting-rust.minikube
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: greeting-rust-service
                port:
                  number: 8080

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: greeting-rust-network-policy
spec:
  podSelector:
    matchLabels:
      app: greeting-rust
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
    name: greeting-rust-cpu-scaledobject
    namespace: default
spec:
    scaleTargetRef:
        name: greeting-rust
    pollingInterval: 10
    cooldownPeriod: 10                               # Optional. Default: 300 seconds
    minReplicaCount: 1
    maxReplicaCount: 10  # Max can go upto num of partitions you have in the topic
    triggers:
        - type: cpu
          metricType: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          metadata:
              value: "50"