apiVersion: apps/v1
kind: Deployment
metadata:
    name: greeting-rust
spec:
    selector:
        matchLabels:
            app: greeting-rust
    template:
        metadata:
            labels:
                app: greeting-rust
        spec:
            containers:
                -   name: greeting-rust
                    image: arnecdn/greeting-rust:0.25
                    imagePullPolicy: IfNotPresent
                    resources:
                        requests:
                            memory: "8Mi"
                            cpu: "1m"
                        limits:
                            memory: "16Mi"
                    ports:
                        -   containerPort: 8080
                    env:

                        - name: APP__KAFKA__BROKER
                          value: "kafka-service:9093"
                        - name: APP__KAFKA__TOPIC
                          value: "greetings"
                        - name: APP__KAFKA__CONSUMER_GROUP
                          value: "greeting_consumers"
                        - name: APP__KAFKA__MESSAGE_TIMEOUT_MS
                          value: "5000"
                        - name: APP__KAFKA__ENABLE_IDEMPOTENCE
                          value: "true"
                    command:
                              - "/usr/bin/server"


---
apiVersion: v1
kind: Service
metadata:
    name: greeting-rust
spec:
    ports:
        - port: 8080
    selector:
        app: greeting-rust
