apiVersion: v1
kind: Service
metadata:
    labels:
        app: kafka-connect
    name: kafka-connect-service
spec:
    type: NodePort
    ports:
        - name: kafka-connect-port1
          port: 8083
          protocol: TCP
          targetPort: 8083
    selector:
        app: kafka-connect
#    clusterIP: None
#    type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: kafka-connect
    name: kafka-connect-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kafka-connect
    template:
        metadata:
            labels:
                app: kafka-connect
        spec:
            containers:
               - image: confluentinc/cp-kafka-connect:latest
                 imagePullPolicy: IfNotPresent
                 name: kafka-connect
                 env:
                      - name: CONNECT_BOOTSTRAP_SERVERS
                        value: "kafka-service:9092"
                      - name: CONNECT_GROUP_ID
                        value: "2"
                      - name: CONNECT_CONFIG_STORAGE_TOPIC
                        value: "quickstart-config"
                      - name: CONNECT_OFFSET_STORAGE_TOPIC
                        value: "quickstart-offsets"
                      - name: CONNECT_STATUS_STORAGE_TOPIC
                        value: "quickstart-status"
                      - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
                        value: "1"
                      - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
                        value: "1"
                      - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
                        value: "1"
                      - name: CONNECT_KEY_CONVERTER
                        value: "org.apache.kafka.connect.json.JsonConverter"
                      - name: CONNECT_VALUE_CONVERTER
                        value: "org.apache.kafka.connect.json.JsonConverter"
                      - name: CONNECT_REST_ADVERTISED_HOST_NAME
                        value: "localhost"
#                 command:
#                     - bash
#                     - -c
#                     - confluent-hub install --no-prompt debezium/debezium-connector-postgresql:2.2.1
#                     - /etc/confluent/docker/run

                 ports:
                     - containerPort: 8083
