apiVersion: v1
kind: Service
metadata:
    labels:
        app: kafka-service
    name: kafka-service
spec:
    type: NodePort
    ports:
        - name: kafka-port
          port: 9092
          protocol: TCP
          targetPort: 9092
          nodePort: 30126
    selector:
        app: kafka
#    clusterIP: None
#    type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: kafka
    name: kafka-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kafka
    template:
        metadata:
            labels:
                app: kafka
        spec:
            containers:
                - env:
                      - name: KAFKA_BROKER_ID
                        value: "1"
                      - name: KAFKA_ZOOKEEPER_CONNECT
                        value: zookeeper-service:2181
                      - name: KAFKA_LISTENERS
                        value: LISTENER_INTERNAL://localhost:9092,LISTENER_EXTERNAL://localhost:30126
                      - name: KAFKA_ADVERTISED_LISTENERS
                        value: LISTENER_INTERNAL://localhost:9092,LISTENER_EXTERNAL://localhost:30126
                      - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
                        value: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
                      - name: KAFKA_INTER_BROKER_LISTENER_NAME
                        value: LISTENER_INTERNAL
                  image: confluentinc/cp-kafka:latest
                  imagePullPolicy: IfNotPresent
                  name: kafka-broker-1
                  ports:
                      - containerPort: 9092
                      - containerPort: 29092