apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-greeting
spec:
    selector:
        matchLabels:
            app: postgres-greeting
    template:
        metadata:
            labels:
                app: postgres-greeting
        spec:
            containers:
                -   name: postgres-greeting
                    image: postgres:14
                    ports:
                        -   containerPort: 5432
                    env:
                        -   name: POSTGRES_DB
                            valueFrom:
                                configMapKeyRef:
                                    key: POSTGRES_DB
                                    name: postgres-greeting-config
                        -   name: POSTGRES_USER
                            valueFrom:
                                configMapKeyRef:
                                    key: POSTGRES_USER
                                    name: postgres-greeting-config
                        -   name: POSTGRES_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    key: POSTGRES_PASSWORD
                                    name: postgres-greeting-secret
#                    command:
#                      - "postgres"
#                      - "-c"
#                      - "wal_level=logical"
---
apiVersion: v1
kind: Service
metadata:
    name: postgres-greeting
spec:
    ports:
        - port: 5432
          targetPort: 5432
    selector:
        app: postgres-greeting
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: postgres-greeting-config
    labels:
        app: postgres-greeting
data:
    POSTGRES_DB: "greeting_rust"
    POSTGRES_USER: "greeting_rust"
    POSTGRES_HOST: "greeting_rust"
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-greeting-secret
    labels:
        app: postgres-greeting
data:
    POSTGRES_PASSWORD: Z3JlZXRpbmdfcnVzdAo=